"""Capability manifest for the public MCP surface."""

from typing import Any

from .version import __version__


def build_tool_manifest(
    official_api: str,
    update_status: dict[str, Any] | None = None,
    backend_compatibility: dict[str, Any] | None = None,
) -> dict:
    """
    返回本 MCP 服务的能力边界、认证方式和建议调用顺序。
    可用于 Agent 在会话开始时自检。
    """
    return {
        "name": "huahua-daily",
        "transport": "stdio",
        "runtime": {
            "version": __version__,
            "updateCheck": update_status or {
                "status": "not_checked",
                "currentVersion": __version__,
                "latestVersion": None,
                "updateAvailable": None,
            },
        },
        "auth": {
            "primary_env": "HUAHUA_AGENT_TOKEN",
            "header": "Authorization: AgentToken <token>",
        },
        "api_base": official_api,
        "backendCompatibility": backend_compatibility or {
            "status": "not_checked",
            "compatible": None,
        },
        "capabilities": {
            "profile": ["get_current_user"],
            "portfolio": [
                "get_sync_meta",
                "get_raw_sync_data",
                "get_records",
                "get_summary",
                "get_transactions",
                "get_groups",
                "get_tags",
                "get_night_watchlist",
                "get_purchase_limit_watchlist",
                "get_auto_invest_plans",
                "get_fund_disciplines",
                "get_transaction_ledger",
                "get_portfolio_nav_history",
                "get_portfolio_trade_review",
            ],
            "quant": [
                "get_batch_fund_nav_history",
                "get_quant_strategy_context",
                "run_portfolio_backtest",
                "get_portfolio_backtest",
                "save_quant_snapshot",
                "get_quant_snapshots",
                "get_quant_snapshot_review",
            ],
            "market": [
                "search_item",
                "get_item_estimate",
                "get_fund_source_previews",
                "get_item_detail",
                "get_item_history",
                "get_item_dividends",
                "get_fund_timeline",
                "get_fund_fees",
                "get_batch_fund_fees",
                "get_fund_period_rank",
                "get_batch_fund_period_ranks",
                "get_fund_profile",
                "get_batch_fund_profiles",
                "get_fund_quant_metrics",
                "get_batch_fund_quant_metrics",
                "get_night_estimate",
                "get_daily_rank",
                "get_status",
                "get_overview",
                "get_sector_wind",
                "get_yesterday_rank",
                "get_fund_flow",
                "get_index_metrics",
                "get_sector_metrics",
                "get_indices",
                "get_holder_ranking",
                "get_benchmark_history",
                "get_instrument_catalog",
                "get_instrument_quotes",
                "get_instrument_timeline",
                "get_instrument_history",
                "calculate_trading_dates",
                "get_next_trading_day",
            ],
            "community": [
                "get_danmaku",
                "send_danmaku",
                "get_notices",
                "get_community_ranking",
                "get_community_my_rank",
                "get_community_user",
                "get_community_stats",
                "get_community_following",
                "search_community_users",
                "get_community_notices",
                "get_community_authorization",
                "authorize_community",
                "revoke_community_authorization",
                "follow_community_user",
            ],
            "trade": ["request_transaction", "get_agent_requests", "update_agent_request"],
            "imports": [
                "import_holding_screenshots",
                "import_transaction_screenshots",
                "request_import_review",
            ],
            "misc": [
                "analyze_jcti",
                "get_app_version",
                "get_app_versions",
            ],
        },
        "safety": {
            "direct_trading": False,
            "trade_flow": "request_transaction 支持买入金额、卖出金额/份额和精确分组，只创建待确认信号，必须由用户在 App 内确认。",
            "trade_request_idempotency": "同一交易或导入请求重试时复用 client_request_id；服务端按当前用户在 7 天窗口内去重。",
            "agent_request_update_boundary": "MCP 只能把待确认请求标记为 DISMISSED；PROCESSED 必须由 App 在用户确认后设置。",
            "direct_state_change_tools": [
                "send_danmaku",
                "authorize_community",
                "revoke_community_authorization",
                "follow_community_user",
                "request_transaction",
                "update_agent_request",
                "request_import_review",
                "run_portfolio_backtest",
                "save_quant_snapshot",
            ],
            "confirmation_required_tools": [
                "send_danmaku",
                "authorize_community",
                "revoke_community_authorization",
                "follow_community_user",
                "request_transaction",
                "update_agent_request",
                "request_import_review",
            ],
            "non_idempotent_toggle_tools": ["follow_community_user"],
            "quant_snapshot_write": True,
            "quant_snapshot_write_boundary": "仅归档 token 所属用户的策略观察；真实持仓、组合版本和内容哈希由服务端捕获，不保存建议金额。",
            "quant_tool_scopes": {
                "get_transaction_ledger": "portfolio:read",
                "get_portfolio_nav_history": "portfolio:read",
                "get_portfolio_trade_review": "portfolio:read",
                "get_batch_fund_nav_history": "market:read",
                "get_fund_quant_metrics": "market:read",
                "get_batch_fund_quant_metrics": "market:read",
                "get_quant_strategy_context": "quant:read",
                "run_portfolio_backtest": "quant:write",
                "get_portfolio_backtest": "quant:read",
                "get_quant_snapshots": "quant:read",
                "get_quant_snapshot_review": "quant:read",
                "save_quant_snapshot": "quant:write",
            },
            "quant_data_basis": "单基金指标使用官方净值 D 日；组合回放使用 linked_daily_return_v1 的 G 日归属；QDII 夜盘仅作执行参考；回测零费率；不宣称严格 point-in-time。",
            "public_report_write": False,
            "cloud_sync_read": "get_records/get_summary/get_raw_sync_data 读取云端实时同步主数据；固定使用结构化组合接口，不读取云端历史备份快照。",
            "estimate_timeout_handling": "timeout、stale last-good 或 estimateDecision=unavailable 的帧不参与当日收益；检查 summary.estimateCompleteness，不能把不可用帧的 0 元当成真实零涨跌。",
            "cloud_sync_write": False,
            "cloud_history_snapshot_write": False,
            "empty_portfolio_restore": "已确认的空组合主数据会被识别为合法可恢复状态，但 MCP 不提供恢复或覆盖写入工具。",
            "destructive_tools": [],
        },
    }
